// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { id: ActionId, atMs: number, } & ({ "type": "tap", x: number, y: number, holdMs: number, } | { "type": "swipe", x0: number, y0: number, x1: number, y1: number, durationMs: number, } | { "type": "key", keycode: string | null, chars: string | null, modifiers: Array<Modifier>, holdMs: number, } | { "type": "mouse_move", x: number | null, y: number | null, dx: number | null, dy: number | null, } | { "type": "mouse_button", button: MouseButton, op: MouseOp, } | { "type": "wait", durationMs: number, });

export type ActionId = string;

export type ActionKind = { "type": "tap", x: number, y: number, holdMs: number, } | { "type": "swipe", x0: number, y0: number, x1: number, y1: number, durationMs: number, } | { "type": "key", keycode: string | null, chars: string | null, modifiers: Array<Modifier>, holdMs: number, } | { "type": "mouse_move", x: number | null, y: number | null, dx: number | null, dy: number | null, } | { "type": "mouse_button", button: MouseButton, op: MouseOp, } | { "type": "wait", durationMs: number, };

export type Clip = { id: ClipId, photoId: PhotoId, startMs: number, durationMs: number, };

export type ClipId = string;

export type EventKind = { "type": "tap", x: number, y: number, hold_ms: number, } | { "type": "swipe", x0: number, y0: number, x1: number, y1: number, duration_ms: number, } | { "type": "key", keycode: string | null, chars: string | null, modifiers: Array<Modifier>, hold_ms: number, } | { "type": "mouse_move", x: number | null, y: number | null, dx: number | null, dy: number | null, } | { "type": "mouse_button", button: MouseButton, op: MouseOp, } | { "type": "wait", duration_ms: number, };

/**
 * USB HID composite profile.
 */
export type HidProfile = "absolute_mouse_keyboard" | "digitizer_keyboard";

export type Modifier = "ctrl" | "shift" | "alt" | "gui";

export type MouseButton = "left" | "right" | "middle";

export type MouseOp = "down" | "up" | "click";

export type Photo = { id: PhotoId, rawPath: string, warpedPath: string | null, corners: [Point, Point, Point, Point] | null, normalized: boolean, width: number, height: number, warpedWidth: number | null, warpedHeight: number | null, };

export type PhotoId = string;

export type Point = { x: number, y: number, };

export type Project = { version: number, name: string, target: Target, photos: Array<Photo>, clips: Array<Clip>, actions: Array<Action>, };

export type RunMode = "auto" | "button" | "serial";

/**
 * On-device `sequence.json` v1 (snake_case).
 */
export type Sequence = { version: number, run_mode: RunMode, settle_ms: number, hid_profile: HidProfile, button_pin: string, events: Array<SequenceEvent>, };

export type SequenceEvent = { at_ms: number, } & ({ "type": "tap", x: number, y: number, hold_ms: number, } | { "type": "swipe", x0: number, y0: number, x1: number, y1: number, duration_ms: number, } | { "type": "key", keycode: string | null, chars: string | null, modifiers: Array<Modifier>, hold_ms: number, } | { "type": "mouse_move", x: number | null, y: number | null, dx: number | null, dy: number | null, } | { "type": "mouse_button", button: MouseButton, op: MouseOp, } | { "type": "wait", duration_ms: number, });

export type Target = { hidProfile: HidProfile, runMode: RunMode, settleMs: number, buttonPin: string, };
